helmsman:
  port: 80
  title: Helmsman
modules:
  - Index_Manager:
    description: Used to manage a private Docker registry.
    enabled: true
    endpoint: repos
    name: Private Registry Manager
  - Host_Manager:
    description: Used to view Docker host information and manage containers.
    enabled: true
    endpoint: hosts/info
    name: Host Manager
docker_hosts:
  - dkrdev01:
    host: dkrdev01.dev.mycompany.com
    port: 4243 
  - dkrdev02:
    host: dkrdev02.dev.mycompany.com
    port: 4243
  - dkrdev03:
    host: dkrdev03.dev.mycompany.com
    port: 4243
registry:
  api_version: v1
  host: localhost
  json_path: json
  port: 5000
  protocol: http://
  repo_path: /v1/repositories
  strip_directory: true
